spring.application.name=smart-kitchen

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_kitchen
spring.datasource.username=postgres
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8081

# Scheduler Configuration
scheduler.concurrency=6
scheduler.max-retries=3
scheduler.polling-delay=1000